<?php

namespace Database\Seeders;

use App\Models\Kategori;
use Illuminate\Database\Seeder;

class CategoryTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $categories = [
            ['VIRTUAL PRODUCT', NULL, NULL],
            ['Pulsa', '3', '6'],
            ['Paket Data', '3', '6'],
            ['Listrik Pasca Bayar', '3', '6'],
            ['Token Listrik', '3', '6'],
            ['BPJS', '3', '6'],
            ['Listrik Pasca Bayar PLN POSTPAID', '4', '28'],
            ['Token Listrik PLN', '4', '28'],
            ['BPJS BPJS', '4', '29'],
            ['Pulsa TELKOMSEL-REGULER', '4', '30'],
            ['Pulsa INDOSAT-REGULER', '4', '30'],
            ['Pulsa XL-REGULER', '4', '30'],
            ['Pulsa AXIS-REGULER', '4', '30'],
            ['Pulsa BOLT-REGULER', '4', '30'],
            ['Pulsa TRI-REGULER', '4', '30'],
            ['Pulsa SMARTFREN-REGULER', '4', '30'],
            ['Paket Data TELKOMSEL-PAKET', '4', '30'],
            ['Paket Data INDOSAT-PAKET', '4', '30'],
            ['Paket Data XL-PAKET', '4', '30'],
            ['Paket Data AXIS-PAKET', '4', '30'],
            ['Paket Data BOLT-PAKET', '4', '30'],
            ['Paket Data TRI-PAKET', '4', '30'],
            ['Paket Data SMARTFREN-PAKET', '4', '30'],
            ['Tas', '3', '9'],
            ['Dekorasi Rumah', '3', '12'],
            ['Busana', '3', '8'],
            ['Aksesori dan Perhiasan', '3', '10'],
            ['Peralatan Masak', '3', '3'],
            ['Peralatan Makan', '3', '4'],
            ['Tempat Makanan & Minuman', '3', '6'],
            ['Health & Beauty', '3', '7'],
            ['Ibu dan Anak', '3', '11'],
            ['Peralatan Rumah Tangga', '3', '2'],
            ['Buku, Mainan & Koleksi', '3', '13'],
            ['Aksesori Handphone dan Komputer', '3', '14'],
            ['Mickey and Friends', '3', '15'],
            ['Disney Movies and Friends', '3', '16'],
            ['Marvel', '3', '17'],
            ['Star Wars', '3', '18'],
            ['Groceries', '3', '5'],
            ['Other Characters', '3', '19'],
            ['Panci', '4', '6'],
            ['Wajan & Fry Pan ', '4', '2'],
            ['Wajan', '4', '66'],
            ['Panggangan', '4', '5'],
            ['Teko', '4', '7'],
            ['Kitchen Utensil', '4', '4'],
            ['Cutlery Set', '4', '94'],
            ['Food Storage', '4', '29'],
            ['Tumbler', '4', '83'],
            ['Tempat Tissue', '4', '39'],
            ['Bowl & Casserole', '4', '93'],
            ['Small Kitchen Appliances', '4', '3'],
            ['Plate', '4', '33'],
            ['Unique Gift & Decorative Ornament', '4', '60'],
            ['Paper Product', '4', '100'],
            ['Face Makeup', '4', '22'],
            ['Pakaian Busana Anak', '4', '96'],
            ['Pakaian TShirt', '4', '67'],
            ['Alat Rumah', '4', '11'],
            ['Tas Ransel', '4', '40'],
            ['Tas Bayi', '4', '37'],
            ['Pakaian Polo Shirt', '4', '70'],
            ['Melamine Mug', '4', '92'],
            ['Unique & Fancy Mug', '4', '35'],
            ['Perawatan Kulit Wajah', '4', '23'],
            ['Pakaian Kemeja', '4', '84'],
            ['Busana Muslim Wanita', '4', '124'],
            ['Koper & Travel Bag', '4', '61'],
            ['Baju Muslim Anak', '4', '125'],
            ['Buku & Mainan Augmented Reality', '4', '50'],
            ['Lipstick', '4', '24'],
            ['Pakaian Foot Wear', '4', '126'],
            ['Fragrance Can', '4', '15'],
            ['Vacuum Flask', '4', '89'],
            ['Toples', '4', '68'],
            ['Lunch Box', '4', '71'],
            ['Bottle', '4', '76'],
            ['Drink Set', '4', '62'],
            ['Pakaian Busana Wanita', '4', '51'],
            ['Ceramic Bowl', '4', '30'],
            ['Ceramic Cup & Saucer', '4', '27'],
            ['Ceramic Mug', '4', '34'],
            ['Ceramic Teapot & Lid', '4', '85'],
            ['Bathroom Scale', '4', '12'],
            ['Kitchen Scale', '4', '10'],
            ['Door Bell', '4', '14'],
            ['Emergency Lamp & Flash Light', '4', '13'],
            ['Home Appliances', '4', '9'],
            ['Mickey Bag', '4', '77'],
            ['Mickey Tin Can', '4', '72'],
            ['Mickey Lunch Box, Tumbler and Bottle', '4', '52'],
            ['Disney Tableware, Mug & Glass', '4', '63'],
            ['Disney Lunch Box, Bottle & Tumbler', '4', '41'],
            ['Disney Tin Can', '4', '53'],
            ['Marvel Adult Fashion', '4', '54'],
            ['Marvel Bag', '4', '78'],
            ['Marvel Kid Fashion', '4', '42'],
            ['Star Wars Lunch Box, Tumbler and Bottle', '4', '64'],
            ['Star Wars Adult Fashion', '4', '55'],
            ['Marvel Lunch Box, Tumbler and Bottle', '4', '73'],
            ['Marvel Accessories & Others', '4', '101'],
            ['Star Wars Kid Fashion', '4', '43'],
            ['Pakaian Jeans', '4', '117'],
            ['Pakaian Sepatu & Sandal Wanita', '4', '120'],
            ['Sunglasses', '4', '56'],
            ['Healthy Food', '4', '20'],
            ['Mickey and Friends Others', '4', '86'],
            ['Paket Product Non Food Alfamart', '4', '87'],
            ['Melamine Tableware', '4', '114'],
            ['Payung & Jas Hujan', '4', '18'],
            ['Pakaian Jaket Pria', '4', '90'],
            ['Pakaian Batik Pria', '4', '79'],
            ['Madu', '4', '49'],
            ['Tableware, Mug & Glass', '4', '58'],
            ['Adult Fashion', '4', '74'],
            ['Mukena', '4', '44'],
            ['Pakaian Baju Muslim Pria', '4', '123'],
            ['Paket Product Food Alfamart', '4', '80'],
            ['Hair Care & Oral Care', '4', '88'],
            ['Pakaian Sepatu & Sandal Pria', '4', '121'],
            ['Pakaian Short pant', '4', '119'],
            ['Pakaian Pant', '4', '118'],
            ['Products Of Our Values Supplier', '4', '113'],
            ['Hair Care & Oral Care Alfamart', '4', '102'],
            ['Cosmetics & Body Care Alfamart', '4', '109'],
            ['Baby Product Alfamart', '4', '108'],
            ['Medicine Product Alfamart', '4', '112'],
            ['Paper Product Alfamart', '4', '111'],
            ['Detergent & Desinfectant Product Alfamart', '4', '98'],
            ['Milk & Beverages Product Alfamart', '4', '47'],
            ['Snack, Chocolate & Confectionary Product Alfamart ', '4', '48'],
            ['Can Food Product Alfamart', '4', '105'],
            ['Staple Needs Product Alfamart', '4', '91'],
            ['Instant Food Product Alfamart', '4', '104'],
            ['Breakfast Food Product Alfamart', '4', '110'],
            ['General Merchandise Alfamart', '4', '95'],
            ['Instant Food', '4', '65'],
            ['Alat Kesehatan', '4', '75'],
            ['Suplemen', '4', '97'],
            ['Pakaian Celana Pria', '4', '116'],
            ['Kasur & Matras', '4', '17'],
            ['Cushion & Cover Character', '4', '81'],
            ['Plasticware', '4', '45'],
            ['General Merchandise', '4', '19'],
            ['Pakaian Sepatu & Sandal Anak', '4', '122'],
            ['Pakaian Balita', '4', '38'],
            ['Kompor & Regulator', '4', '1'],
            ['Surfer Girl', '4', '103'],
            ['Cigarette & Lighter', '4', '107'],
            ['Ice Cream', '4', '106'],
            ['Mug', '4', '32'],
            ['Water Jug', '4', '99'],
            ['Plastic Furniture', '4', '69'],
            ['Body Care', '4', '82'],
            ['Alfamart Promo', '4', '26'],
            ['Alfamart Festive', '4', '46'],
            ['SALE! Peralatan Masak', '4', '59'],
            ['Eye Make Up', '4', '21'],
            ['Tempat Nasi', '4', '36'],
            ['Melamine Plate', '4', '31'],
            ['Peralatan Olahraga', '4', '25'],
            ['Sub Category Contoh', '4', '127'],
            ['GO PAY VOUCHER GO-PAY-CUSTOMER', '4', NULL],
            ['Store jgn delete', '4', '127'],
            ['Arisan', '4', '128'],
            ['Makanan & Minuman', '3', '20'],
            ['Snack', '4', '131'],
            ['Melamine Bowl ', '4', '133'],
            ['Handphone & Tablet', '3', '1'],
            ['Handphone', '4', '134'],
            ['HP (ARISAN)', '4', '135'],
            ['Sprei & Bedcover', '4', '16'],
            ['Jam Tangan', '4', '136'],
            ['Furniture', '4', '8'],
            ['Tas Makeup & Organizer', '4', '137'],
            ['Bracket', '4', '138'],
            ['Bath Towel', '4', '139'],
            ['Dompet / Clutch', '4', '140'],
            ['Keset', '4', '141'],
            ['Kabel Data', '4', '142'],
            ['Power Adapter', '4', '143'],
            ['Case dan Covers', '4', '144'],
            ['Collagen', '4', '145'],
            ['Perkakas', '4', '146']
        ];

        foreach ($categories as $key => $category) {
            Kategori::create([
                "name" => $categories[$key][0],
                "nest_level" => $categories[$key][1],
                "sort_order" => $categories[$key][2]
            ]);
            $this->command->info($categories[$key][0] . "created !");
        }
    }
}
